sourceregistry:
  url: http://localhost:5000
  username:
  password: 
  type: docker
destinationregistry:
  url: https://docker.io
  username: mangirdas
  password: xxxxxxxxx
  type: docker
insecurepolicy: true
registriesdirpath: registries.d
dockerinsecureskiptlsverify: true
namespacemap:
- source: openshift3
  destination: mangirdas
